### ISSUE TITLE
Timeline for upgrading pyth-sdk-solana

### ISSUE THREAD

**Issue by nickguo** [pyth-network/pyth-sdk-rs#110]
Hello, the latest `pyth-sdk-solana v0.7.2` only supports up to `solana-program v0.15`.

I saw that `pyth-sdk v0.8.0` was updated to support solana 1.16.  Is there work in progress to support solana 1.16?
There is some inconsistencies with borsch 0.9.3 and 0.10.3 that was causing issues

**Comment by guibescos** [comment]
Thanks so much for reporting! Seems like the release for 0.8.0 had not been triggered, are you still encountering the error?

**Comment by wjthieme** [comment]
Works now!

**Comment by nickguo** [comment]
Fantastic thank you @guibescos !  As @wjthieme reported, my project is also now working with `pyth-sdk-solana 0.8.0` and `solana-program 1.16.8`

**Comment by nickguo** [comment]
Resolved 🙏

**Comment by Yuanye** [comment]
It will result in a version conflict with `zeroize` when using `sea-orm 0.12.*` and `solana-program 1.16.*`. It is necessary to update `solana-program` in order to resolve inconsistencies with `borsh-derive` 0.9.3 and 0.10.3.
