### ISSUE TITLE
Can't install pyth-sdk-solana depencendy

### ISSUE THREAD

**Issue by Asaki-Katsu** [pyth-network/pyth-sdk-rs#116]
I'm trying to install `pyth-sdk-solana` sdk into my rust project for fetching price off-chain.

All I did is just put the config into my Cargo.toml
```
pyth-sdk-solana = "=0.0.8" 
```

But I failed to build, when trying to run `cargo build` I got this error.
![Screenshot 2567-03-06 at 13 29 47](https://github.com/pyth-network/pyth-sdk-rs/assets/138423682/5f982a70-2126-4f6e-a297-ce759be94828)

Do I need to install other dependencies manually ?

**Comment by guibescos** [comment]
I can't quite reproduce, it seems cargo is fetching two different and incompatible versions of [borsh](https://crates.io/crates/borsh)

**Comment by guibescos** [comment]
Please reopen and provide steps to reproduce if you still encounter the issue.
