### ISSUE TITLE
AccountInfo for on-chain price consume

### ISSUE THREAD

**Issue by luke4u** [pyth-network/pyth-sdk-rs#57]
Hi - could you give an dummy example on how to construct AccountInfo for on-chain price consume? Thank you!

**Comment by ali-bahjati** [comment]
Hey, I believe in solana the accounts that are passed to the instruction processor are AccountInfo. We will soon add more examples to this repo.

**Comment by luke4u** [comment]
Hi, thank you! just need some dummy examples on the accounts! Looking forward to your updates.

**Comment by luke4u** [comment]
@ali-bahjati , I am trying to create an instance of AccountInfo, but not sure how to do. Do you mind give a bit help? Below is I got so far. Thanks so much!

```
let key = String::from("45gMLT6mGfa8aJFeA97Cg65tp1qJZriHkmkucd3TbQZ8");
let pub_key: Pubkey = Pubkey::from_str(&key).unwrap();

let price_account_info: AccountInfo = AccountInfo {
    key: &pub_key,
    is_signer: true,
    is_writable: false,
    lamports: ? ,
    data: ?,
    executable: false,
    owner: &pub_key,
    rent_epoch: 2,
};
```

**Comment by ali-bahjati** [comment]
Hi @luke4u,

You should not create it by yourself, in solana when you call a program you pass account info s as argument and then you can just use them right away. [this example](https://paulx.dev/blog/2021/01/14/programming-on-solana-an-introduction/) is a bit old but definitely helpful with only solana. However I recommend you to use Anchor which makes it simpler. You can start by reading their book [here](https://book.anchor-lang.com/introduction/introduction.html)

**Comment by luke4u** [comment]
thank you so much for the help!
