### ISSUE TITLE
Question: Breaking changes in v0.7

### ISSUE THREAD

**Issue by nevi-me** [pyth-network/pyth-sdk-rs#92]
Hello Pyth developers :) 

The PR #77 from @ali-bahjati was a breaking change relative to 0.6, so I requested a release of 0.7. Thank you for that.

We noticed while reviewing the change on our code to update to 0.7, that there's a big change to `PriceFeed` (https://github.com/pyth-network/pyth-sdk-rs/commit/4f4f8c79efcee6402a94dd81a0aa1750a1a12297#diff-a65a7eeb4bb0903ac59ac4c4d43a6829364bc0b9136830ccc155a59d1b2720c3L135-L176).

Question: It looks like the change would result in a breaking change in the data that we'd read on chain, is this correct, and should projects remain on the 0.6 branch until some point in the future if so?

Or are there imminent plans to deploy the change (or has it been deployed)?

Thanks

**Comment by ali-bahjati** [comment]
@nevi-me Thanks for opening this issue. It's a good question. Indeed it is a breaking api change and thank you for bumping to `0.7.0`. However, this is only the api for consumers of the data, we have not changed the on-chain state data structure (they are defined in the [state](https://github.com/pyth-network/pyth-sdk-rs/blob/main/pyth-sdk-solana/src/state.rs) module). So this should be fine.

I'm closing this issue, please reopen it does not answer your question or there is any other issue that I missed.
